### PR TITLE
Browser testing

### PR DESCRIPTION
**Pull request by davidroberts63**
Browser testing Bluefin against two versions of Octopus Deploy.
Uses Azure VMs, Jasmine tests, Selenium Webdriver npm, and Sauce Labs for the desktop.

Currently working on a Readme for this.

### CODE REVIEW

**Comment by davidroberts63** [comment]
:x: [Build chrome-extension 1.0.62 failed](https://ci.appveyor.com/project/BluefinOctopusDeploy/chrome-extension/build/1.0.62) (commit https://github.com/bluefin-octopusdeploy/chrome-extension/commit/6fd2db2249 by @davidroberts63)

**Comment by davidroberts63** [comment]
:x: [Build chrome-extension 1.0.64 failed](https://ci.appveyor.com/project/BluefinOctopusDeploy/chrome-extension/build/1.0.64) (commit https://github.com/bluefin-octopusdeploy/chrome-extension/commit/aca103c2e7 by @davidroberts63)

**Comment by davidroberts63** [comment]
:x: [Build chrome-extension 1.0.66 failed](https://ci.appveyor.com/project/BluefinOctopusDeploy/chrome-extension/build/1.0.66) (commit https://github.com/bluefin-octopusdeploy/chrome-extension/commit/330d0aef7d by @davidroberts63)

**Comment by davidroberts63** [comment]
The test failure in there is one I purposefully put in to verify the failure aspect. It's showing that there's a problem with the target/machine filtering in 3.3+. I'll address that issue after this gets merged.

**Comment by davidroberts63** [comment]
Also, I don't know who wankyoung is nor how Github thinks that's who I was. I probably messed up my local git config email setting.

**Comment by matt-richardson** [comment]
> I probably messed up my local git config email setting.

If you squash your commits, you should be able to rewrite so its all attributed to you...

**Comment by matt-richardson** [comment]
Liking the look of it. Hope I can find the time to add some tests for the stuff I wrote.

Why are there 4 checks (2 travis + 2 appveyor) here?

**Comment by davidroberts63** [comment]
Yeah not sure why there are four. I'm going to look into that.

**Comment by davidroberts63** [comment]
I'll be merging this tomorrow night GMT-5. I think it's done enough to get some more tests in place and running locally.

The Azure bit...bit. So I'm looking elsewhere. Perhaps atlantic.net. But I want browser tests now.

**Comment by matt-richardson** [comment]
Would be worth chatting about a bit before giving up - multiple versions work, but probably not when installed via the msi.
Also, if thats not working out, we could also take a look at going down the docker route...?

**Comment by davidroberts63** [comment]
Docker route definitely, or multi version install. Just feel I'm spending
more time on that part than getting browser tests working for the benefit
they provide. At least they can be run locally against multiple VMs.

Do you know if windows containers will work on 2012r2?

On Oct 8, 2016 4:38 AM, "Matt Richardson" <notifications@github.com> wrote:

Would be worth chatting about a bit before giving up - multiple versions
work, but probably not when installed via the msi.
Also, if thats not working out, we could also take a look at going down the
docker route...?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/bluefin-octopusdeploy/chrome-extension/pull/69#issuecomment-252415020>,
or mute the thread

**Comment by matt-richardson** [comment]
Nope, containers are only on Win10 (anniversary edition) or Win2016.

**Pull request merged**
