### PR TITLE
Pass in octopusVersion parameter.

### LINKED ISSUE #85: 'Update All' for referencing projects after template step update has disappeared
In the most recent version, 1.52.18, 'Update All' link, under Library > Step Templates > {templateName} > Usage, has disappeared. The page still displays a list of all projects using the template step, along with Step, Version, and column indicating 'Out of date'.

### PR DESCRIPTION
**Pull request by matt-richardson**
Forgot to pass it in. I think it might have broken a few things - edit step as json, clone step and more.
 
Fixes #85.

### CODE REVIEW

**Comment by davidroberts63** [comment]
Yeah, I fell bad that I missed that.

**Comment by BinLiuSeattle** [comment]
I see 'Update All' button now appears. But it appears even when all projects are 'Up to date'. I can't recall whether it was like this before. Just a heads up.

**Comment by davidroberts63** [comment]
Hmmm. I'll check on that, I don't recall off the top of my mind.

**Comment by matt-richardson** [comment]
Looking at [the code](https://github.com/bluefin-octopusdeploy/chrome-extension/blob/master/src/3.0/step-template-updater.js#L59), there never was any provision for conditionally showing the update button. That said, it wouldn't be too difficult to do, just gotta find the time...

**Pull request merged**
